
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 3;
  public static final int WS = 9;
  public static final int BOOL = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int STRING = 6;
  public static final int OPENBRACKET = 7;
  public static final int DOUBLE = 4;
  public static final int error = 1;
  public static final int STRINGLITERAL = 11;
  public static final int IDENTIFIER = 10;
  public static final int CLOSEBRACKET = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "WS",
  "IDENTIFIER",
  "STRINGLITERAL"
  };
}

